version: "3.8"

services:
  site:
    build: .
    container_name: site-node
    restart: always
    environment:
      - VIRTUAL_HOST=saumondeluxe.com
      - LETSENCRYPT_HOST=saumondeluxe.com
      - LETSENCRYPT_EMAIL=planque.adam@gmail.com
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external: true
